#
#
# vagrant box add --name rhel/7 --force  rhel-7.4.box
# SMB account name when using MS account : MicrosoftAccount\me@email.com

# sudo subscription-manager register --auto-attach
# sudo subscription-manager remove --all
# sudo subscription-manager unregister
# sudo subscription-manager clean
# $env:VAGRANT_LOG= 'warn'
Vagrant.configure("2") do |config|
  config.vm.box = "rhel/7"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "DMZ"
  config.vm.synced_folder ".", "/vagrant", disabled: false, type: "rsync", rsync__exclude: [".git/", "*.box", "*.iso", "output-*/", "packer_cache/", "http/"]
end
